<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Entity\Conference' shared autowired service.

include_once $this->targetDirs[3].'/src/Entity/Conference.php';

return $this->services['App\Entity\Conference'] = new \App\Entity\Conference();
