<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Entity\Homepage' shared autowired service.

include_once $this->targetDirs[3].'/src/Entity/Homepage.php';

return $this->services['App\Entity\Homepage'] = new \App\Entity\Homepage();
