<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.KCyM7pa' shared service.

return $this->privates['service_locator.KCyM7pa'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('authorizationChecker' => function () {
    return ($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService());
}, 'conference' => function (): ?\App\Entity\Conference {
    return ($this->services['App\Entity\Conference'] ?? $this->services['App\Entity\Conference'] = new \App\Entity\Conference());
}));
