<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\ConferenceController:deleteConference' => function () {
    return ($this->privates['service_locator.l.KMwXM'] ?? $this->load(__DIR__.'/getServiceLocator_L_KMwXMService.php'));
}, 'App\\Controller\\ConferenceController:editConference' => function () {
    return ($this->privates['service_locator.KCyM7pa'] ?? $this->load(__DIR__.'/getServiceLocator_KCyM7paService.php'));
}, 'App\\Controller\\ConferenceController:newConference' => function () {
    return ($this->privates['service_locator.ujxsWnj'] ?? $this->load(__DIR__.'/getServiceLocator_UjxsWnjService.php'));
}, 'App\\Controller\\ConferenceController:showConference' => function () {
    return ($this->privates['service_locator.PEURVel'] ?? $this->load(__DIR__.'/getServiceLocator_PEURVelService.php'));
}, 'App\\Controller\\HomepageController:editHomepage' => function () {
    return ($this->privates['service_locator.YCAiwcp'] ?? $this->load(__DIR__.'/getServiceLocator_YCAiwcpService.php'));
}, 'App\\Controller\\HomepageController:newHomepage' => function () {
    return ($this->privates['service_locator.rLRd4h0'] ?? $this->load(__DIR__.'/getServiceLocator_RLRd4h0Service.php'));
}, 'App\\Controller\\SecurityController:check_register' => function () {
    return ($this->privates['service_locator.L9khF0Y'] ?? $this->load(__DIR__.'/getServiceLocator_L9khF0YService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['service_locator.KELS8pk'] ?? $this->load(__DIR__.'/getServiceLocator_KELS8pkService.php'));
}, 'App\\Controller\\ConferenceController::deleteConference' => function () {
    return ($this->privates['service_locator.l.KMwXM'] ?? $this->load(__DIR__.'/getServiceLocator_L_KMwXMService.php'));
}, 'App\\Controller\\ConferenceController::editConference' => function () {
    return ($this->privates['service_locator.KCyM7pa'] ?? $this->load(__DIR__.'/getServiceLocator_KCyM7paService.php'));
}, 'App\\Controller\\ConferenceController::newConference' => function () {
    return ($this->privates['service_locator.ujxsWnj'] ?? $this->load(__DIR__.'/getServiceLocator_UjxsWnjService.php'));
}, 'App\\Controller\\ConferenceController::showConference' => function () {
    return ($this->privates['service_locator.PEURVel'] ?? $this->load(__DIR__.'/getServiceLocator_PEURVelService.php'));
}, 'App\\Controller\\HomepageController::editHomepage' => function () {
    return ($this->privates['service_locator.YCAiwcp'] ?? $this->load(__DIR__.'/getServiceLocator_YCAiwcpService.php'));
}, 'App\\Controller\\HomepageController::newHomepage' => function () {
    return ($this->privates['service_locator.rLRd4h0'] ?? $this->load(__DIR__.'/getServiceLocator_RLRd4h0Service.php'));
}, 'App\\Controller\\SecurityController::check_register' => function () {
    return ($this->privates['service_locator.L9khF0Y'] ?? $this->load(__DIR__.'/getServiceLocator_L9khF0YService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['service_locator.KELS8pk'] ?? $this->load(__DIR__.'/getServiceLocator_KELS8pkService.php'));
})));
