<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Event\HomepageEvent' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/event-dispatcher/Event.php';
include_once $this->targetDirs[3].'/src/Event/HomepageEvent.php';

return $this->services['App\Event\HomepageEvent'] = new \App\Event\HomepageEvent();
