<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\ConferenceController:deleteConference' => function () {
    return ($this->privates['service_locator.l.KMwXM'] ?? $this->load(__DIR__.'/getServiceLocator_L_KMwXMService.php'));
}, 'App\\Controller\\ConferenceController:editConference' => function () {
    return ($this->privates['service_locator.KCyM7pa'] ?? $this->load(__DIR__.'/getServiceLocator_KCyM7paService.php'));
}, 'App\\Controller\\ConferenceController:newConference' => function () {
    return ($this->privates['service_locator.ujxsWnj'] ?? $this->load(__DIR__.'/getServiceLocator_UjxsWnjService.php'));
}, 'App\\Controller\\ConferenceController:showConference' => function () {
    return ($this->privates['service_locator.PEURVel'] ?? $this->load(__DIR__.'/getServiceLocator_PEURVelService.php'));
}, 'App\\Controller\\ConferenceController::deleteConference' => function () {
    return ($this->privates['service_locator.l.KMwXM'] ?? $this->load(__DIR__.'/getServiceLocator_L_KMwXMService.php'));
}, 'App\\Controller\\ConferenceController::editConference' => function () {
    return ($this->privates['service_locator.KCyM7pa'] ?? $this->load(__DIR__.'/getServiceLocator_KCyM7paService.php'));
}, 'App\\Controller\\ConferenceController::newConference' => function () {
    return ($this->privates['service_locator.ujxsWnj'] ?? $this->load(__DIR__.'/getServiceLocator_UjxsWnjService.php'));
}, 'App\\Controller\\ConferenceController::showConference' => function () {
    return ($this->privates['service_locator.PEURVel'] ?? $this->load(__DIR__.'/getServiceLocator_PEURVelService.php'));
})));
