<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.ujxsWnj' shared service.

return $this->privates['service_locator.ujxsWnj'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('authorizationChecker' => function () {
    return ($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService());
}));
