<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.YCAiwcp' shared service.

return $this->privates['service_locator.YCAiwcp'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('authorizationChecker' => function () {
    return ($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService());
}, 'homepage' => function (): ?\App\Entity\Homepage {
    return ($this->services['App\Entity\Homepage'] ?? $this->services['App\Entity\Homepage'] = new \App\Entity\Homepage());
}));
