<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6LM8Isj\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6LM8Isj/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container6LM8Isj.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container6LM8Isj\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container6LM8Isj\srcDevDebugProjectContainer(array(
    'container.build_hash' => '6LM8Isj',
    'container.build_id' => '632f6e49',
    'container.build_time' => 1516803593,
));
