<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerElKkFMH\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerElKkFMH/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerElKkFMH.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerElKkFMH\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerElKkFMH\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ElKkFMH',
    'container.build_id' => 'fde4b409',
    'container.build_time' => 1517522901,
));
