<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRgYRlBl\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRgYRlBl/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRgYRlBl.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRgYRlBl\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerRgYRlBl\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'RgYRlBl',
    'container.build_id' => '7305fd2f',
    'container.build_time' => 1518373324,
));
